// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyHULm8TCju4-fpZ66kXMVLClvBsMe9u8',
    appId: '1:360879063650:web:c7f55f6bb7fe6126c2073b',
    messagingSenderId: '360879063650',
    projectId: 'shopease-2089e',
    authDomain: 'shopease-2089e.firebaseapp.com',
    storageBucket: 'shopease-2089e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHtiEmUo6MjR5kS61FZfiiWrkdaajkQJM',
    appId: '1:360879063650:android:a973e5869fe7912cc2073b',
    messagingSenderId: '360879063650',
    projectId: 'shopease-2089e',
    storageBucket: 'shopease-2089e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyHULm8TCju4-fpZ66kXMVLClvBsMe9u8',
    appId: '1:360879063650:web:bbe643dff397aee9c2073b',
    messagingSenderId: '360879063650',
    projectId: 'shopease-2089e',
    authDomain: 'shopease-2089e.firebaseapp.com',
    storageBucket: 'shopease-2089e.firebasestorage.app',
  );
}
